application: proiect
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /markitup
  static_dir: markitup

- url: /.*
  script: proiect-987.app


libraries:
- name: jinja2
  version: latest
